Repository Gyokuro-cha/landmine, pull requests merged in 2020-10, with the labels that each got.

#1 Readme
  README.md
Labels: documentation, hacktoberfest-accepted

#2 Add list
  README.md
  list.js
Labels: documentation, enhancement, hacktoberfest-accepted

#3 deleting some words
  list.js
Labels: enhancement, hacktoberfest-accepted

#5 Added Page
  list.js
Labels: enhancement, hacktoberfest-accepted

#4 add new page
  list.js
Labels: enhancement, hacktoberfest-accepted
